name: Lets Start EmceeBot
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "MashaRoBot"
          replace: "EmceeBot"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Emcee✨'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: Aquila-14
          commit_user_email: aj556934@gmail.com
          
